name: '[C#] Logging Release'

on:
  workflow_run:
    workflows:
      - '\[C#\] Logging CI'
    types:
      - completed
    branches:
      - 'release-*'

permissions:
  contents: write

defaults:
  run:
    shell: bash

jobs:
  release:
    if: github.repository == 'godaddy/asherah' && github.event.workflow_run.conclusion == 'success'
    name: Release C# Logging
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
        with:
          ref: ${{ github.event.workflow_run.head_branch }}

      - name: Fetch all tags
        run: git fetch --prune --unshallow --tags

      - name: Cache dotnet packages
        uses: actions/cache@1bd1e32a3bdc45362d1e726936510720a7c30a57 # v4.2.0
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('csharp/**/*.csproj') }}-v2

      - name: Download artifact
        run: |
          gh run download ${RUN_ID} --repo godaddy/asherah --dir ${TARGET_DIR} --name csharp-logging
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TARGET_DIR: ${{ github.workspace }}/csharp/Logging/Logging
          RUN_ID: ${{ github.event.workflow_run.id }}

      - name: Initialize Envionment Variables
        run: |
          echo "BASE_VERSION=$(grep -o '<Version>.*<.*>' Directory.Build.props | sed 's/<Version>\(.*\)<.*>/\1/')" >> $GITHUB_ENV
          echo "VERSION_SUFFIX=$(echo ${BASE_VERSION} | cut -f2 -d'-')" >> $GITHUB_ENV
          echo "BRANCH=${{ github.event.workflow_run.head_branch }}" >> $GITHUB_ENV
          echo "GITHUB_SHA=${{ github.event.workflow_run.head_sha }}" >> $GITHUB_ENV
        working-directory: csharp/Logging

      - name: Publish C# Logging
        if: startsWith(github.env.BRANCH, 'release-') && github.env.VERSION_SUFFIX != 'alpha'
        run: |
          ./scripts/release_prod.sh
        env:
          NUGET_KEY: ${{ secrets.NUGET_KEY }}
          NUGET_SOURCE: ${{ secrets.NUGET_SOURCE }}
        working-directory: csharp/Logging
