name: '[Java] Run All'

on:
  workflow_dispatch:

  # TODO: remove the push trigger before merging
  push:
    paths:
      - 'java/app-encryption/**'
      - '.github/workflows/java-*'

jobs:
  securememory-main:
    name: 'SecureMemory: Build & Test'
    uses: ./.github/workflows/java-securememory-ci.yml
    with:
      java-version: '17'

  appencryption-main:
    name: 'AppEncryption: Build & Test'
    needs: securememory-main
    uses: ./.github/workflows/java-appencryption-ci.yml
    with:
      java-version: '17'

  appencryption-integration:
    name: 'AppEncryption: Integration'
    needs: appencryption-main
    uses: ./.github/workflows/java-appencryption-integration.yml
    with:
      java-version: '17'

  reference-app:
    runs-on: ubuntu-latest
    needs: appencryption-main
    steps:
      - name: Checkout repository
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

      - name: Set up Java
        uses: actions/setup-java@99b8673ff64fbf99d8d325f52d9a5bdedb8483e9 # v4.2.1
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'
          cache-dependency-path: 'java/*/pom.xml'

      - name: Build
        run: |
          cd samples/java/reference-app
          ./scripts/clean.sh
          ./scripts/build.sh

  server:
    name: 'Server: Build & Test'
    runs-on: ubuntu-latest
    needs: appencryption-main
    steps:
      - name: Checkout repository
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

      - name: Set up Java
        uses: actions/setup-java@99b8673ff64fbf99d8d325f52d9a5bdedb8483e9 # v4.2.1
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'
          cache-dependency-path: 'java/*/pom.xml'

      - name: Build
        run: |
          cd server/java
          ./scripts/clean.sh
          ./scripts/build.sh

      - name: Run unit tests
        run: |
          cd server/java
          sudo prlimit --pid $$ --core=-1
          sudo prlimit --pid $$ --memlock=-1:-1
          ./scripts/test.sh
